version: '1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - rabbitmq_go_net
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 10s
        retries: 5
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: /Dockerfile.api
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ApiProcess.pfx
    volumes:
    - ~/.aspnet/https:/https:ro
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
        - rabbitmq_go_net
  worker-a:
    image: ${DOCKER_REGISTRY-}worker-a
    build:
      context: .
      dockerfile: /Dockerfile.worker-a
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
        - rabbitmq_go_net
    links: 
        - rabbitmq
          
networks:
  rabbitmq_go_net:
    driver: bridge