version: '1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - rabbitmq_go_net
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 10s
        retries: 5
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    container_name: sqlserver
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - '11433:1433'    
    expose:
      - 1433
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PyourStrong(!)Password", "-Q", "select 1"]
      interval: 1s
      retries: 20
    networks:
      - rabbitmq_go_net
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: /Dockerfile.api
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ApiProcess.pfx
    volumes:
    - ~/.aspnet/https:/https:ro
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
      - rabbitmq_go_net
  worker-a:
    image: ${DOCKER_REGISTRY-}worker-a
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: /Dockerfile.worker-a
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_go_net
    links: 
      - rabbitmq
          
networks:
  rabbitmq_go_net:
    driver: bridge