version: '1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - rabbitmq_go_net
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ../Dockerfile.api
    depends_on:
      - rabbitmq
    ports:
      - "5058:5058"
    networks:
        - rabbitmq_go_net
  worker-a:
    image: ${DOCKER_REGISTRY-}worker-a
    build:
      context: .
      dockerfile: ../Dockerfile.worker-a
    depends_on:
      - rabbitmq
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge